apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-basic-auth
type: {{ .Values.secret.type }}
stringData:
  username: {{ .Values.secret.username }} 
  password: {{ .Values.secret.password }} 